import json
import os
import traceback
from typing import Dict, Any, List

import db
import pipeline

# Failure taxonomy constants
EXTRACTION_HALLUCINATION = "Extraction Hallucination"
MISCLASSIFICATION = "Misclassification"
PROPAGATION_ERROR = "Propagation Error"
PROMPT_FAILURE = "Prompt Failure"
CONTEXT_LOSS = "Context Loss"

def evaluate_span(step_name: str, input_data: str, output_data: str) -> Dict[str, Any]:
    """Uses LLM-as-judge to score a single span's output based on its input."""
    prompt = f"""
    You are an AI quality judge. Evaluate the output of a pipeline step named '{step_name}' given its input.
    Compare the input data with the output data. Check for hallucinations, omissions, format errors, or logical mistakes.

    Input Data:
    {input_data}

    Output Data:
    {output_data}

    Provide your analysis in JSON format with the following keys:
    - "score": 1-5 (5: perfect, 4: minor issues, 3: moderate errors but usable, 2: major errors/hallucinations, 1: completely wrong or crashed)
    - "is_propagation": true/false (Is the error in this output primarily caused by bad input fields that were generated by an earlier step? Select true if this step processed its inputs correctly but the inputs themselves were already incorrect. Select false if this step made its own error.)
    - "explanation": "Detailed explanation of your evaluation."
    """
    
    system_prompt = "You evaluate AI pipeline step quality. You output ONLY valid JSON matching the requested keys."
    
    try:
        raw_response, _ = pipeline.call_llm(prompt, system_prompt)
        cleaned = pipeline.clean_json_response(raw_response)
        result = json.loads(cleaned)
        return {
            "score": int(result.get("score", 5)),
            "is_propagation": bool(result.get("is_propagation", False)),
            "explanation": str(result.get("explanation", "No explanation provided."))
        }
    except Exception as e:
        print(f"LLM Judge evaluate_span failed: {e}. Falling back to rule-based evaluation.")
        # Local fallback evaluation rules
        return run_local_span_evaluation(step_name, input_data, output_data)

def run_local_span_evaluation(step_name: str, input_data: str, output_data: str) -> Dict[str, Any]:
    """Rule-based local fallback evaluation when LLM-as-judge is unavailable."""
    score = 5
    is_propagation = False
    explanation = "Rule-based evaluation: Step completed successfully."
    
    try:
        in_dict = json.loads(input_data) if isinstance(input_data, str) else input_data
        out_dict = json.loads(output_data) if isinstance(output_data, str) else output_data
    except:
        in_dict = {}
        out_dict = {}

    if not out_dict:
        score = 1
        explanation = "Step output is empty or failed to parse."
        return {"score": score, "is_propagation": is_propagation, "explanation": explanation}

    # Check for failure injection keywords or indicators
    input_str_lower = str(input_data).lower()
    
    if step_name == "Intake":
        if "fail_intake" in input_str_lower:
            score = 1
            explanation = "Sanitization failed: Input text was corrupted."
    elif step_name == "Extraction":
        confidence = out_dict.get("confidence", 5)
        vendor = out_dict.get("vendor", "")
        if "fail_extraction_hallucination" in input_str_lower:
            score = 2
            explanation = "Extracted invoice amount is 10x larger than what is indicated in the text (Hallucination)."
        elif "fail_extraction_missing" in input_str_lower or vendor == "N/A" or confidence <= 2:
            score = 2
            explanation = "Failed to extract required fields (vendor name, date) from the document."
    elif step_name == "Classification":
        confidence = out_dict.get("confidence", 5)
        category = out_dict.get("category", "")
        if "fail_misclassify" in input_str_lower or confidence <= 2:
            score = 2
            explanation = f"Misclassified document as '{category}' when it is a Purchase Order."
        # If extraction was already bad, check if this is propagation
        if "fail_extraction" in input_str_lower:
            is_propagation = True
            score = 4
            explanation = "Classification was successful but processed fields containing errors from the extraction step."
    elif step_name == "Summarization":
        confidence = out_dict.get("confidence", 5)
        if "fail_context_loss" in input_str_lower or confidence <= 2:
            score = 2
            explanation = "The summary is too brief and missed key payment terms and action items."
        elif "fail_extraction" in input_str_lower:
            is_propagation = True
            score = 3
            explanation = "The summary contains propagation errors, referencing incorrect invoice total from the extraction step."

    return {
        "score": score,
        "is_propagation": is_propagation,
        "explanation": explanation
    }

def diagnose_root_cause(raw_text: str, evaluations: Dict[str, Dict[str, Any]]) -> Dict[str, Any]:
    """Diagnoses the root cause and failure type of the overall trace based on step evaluations."""
    prompt = f"""
    You are a Failure Forensics Expert for AI pipelines. Review the raw document text, the step evaluations, and diagnose the root cause of the failure.

    Document Text:
    {raw_text}

    Step Evaluations:
    {json.dumps(evaluations, indent=2)}

    Taxonomy definitions:
    - Extraction Hallucination: The extraction step hallucinated, misread, or fabricated values (e.g. amount, vendor, date) from the source document.
    - Misclassification: The classification step assigned the incorrect category/type to the document.
    - Propagation Error: A downstream step (e.g. Classification, Summarization) produced an incorrect output because it relied on incorrect input fields from an upstream step.
    - Prompt Failure: The LLM failed to follow the format instructions (e.g., failed to output JSON, crashed, or didn't output required fields).
    - Context Loss: The summarization step omitted critical details, deadlines, or action items present in the source text.

    Provide your diagnosis in JSON format with the following keys:
    - "root_cause_step": "The name of the step where the error first originated (Intake, Extraction, Classification, or Summarization)."
    - "root_cause_type": "One of the taxonomy categories above."
    - "explanation": "A clear, detailed explanation of how the error originated and how it propagated downstream (the evidence chain)."
    """
    
    system_prompt = "You diagnose AI pipeline root causes. You output ONLY valid JSON matching the requested keys."
    
    try:
        raw_response, _ = pipeline.call_llm(prompt, system_prompt)
        cleaned = pipeline.clean_json_response(raw_response)
        result = json.loads(cleaned)
        return {
            "root_cause_step": str(result.get("root_cause_step", "Unknown")),
            "root_cause_type": str(result.get("root_cause_type", "Unknown")),
            "explanation": str(result.get("explanation", "No explanation provided."))
        }
    except Exception as e:
        print(f"LLM Judge diagnose_root_cause failed: {e}. Falling back to rule-based diagnosis.")
        return run_local_root_cause_diagnosis(raw_text, evaluations)

def run_local_root_cause_diagnosis(raw_text: str, evaluations: Dict[str, Dict[str, Any]]) -> Dict[str, Any]:
    """Rule-based local fallback diagnosis when LLM-as-judge is unavailable."""
    text_lower = str(raw_text).lower()
    
    # Check evaluations in normal execution order: Intake -> Extraction -> Classification -> Summarization
    # The first step that has a score < 4 is the root cause!
    steps_order = ["Intake", "Extraction", "Classification", "Summarization"]
    
    failing_step = "Unknown"
    failing_type = "Unknown"
    explanation = "No failures detected in step evaluations."
    
    for step in steps_order:
        eval_data = evaluations.get(step)
        if not eval_data:
            continue
            
        score = eval_data.get("score", 5)
        is_propagation = eval_data.get("is_propagation", False)
        
        # If the step failed or had a quality drop, and it was not a propagation error
        if score < 4 and not is_propagation:
            failing_step = step
            if step == "Intake":
                failing_type = PROMPT_FAILURE
                explanation = "Intake step failed to sanitize inputs due to document format corruption."
            elif step == "Extraction":
                if "fail_extraction_hallucination" in text_lower:
                    failing_type = EXTRACTION_HALLUCINATION
                    explanation = "Extraction step hallucinated an incorrect amount (10x higher). This amount propagated to Summarization."
                else:
                    failing_type = EXTRACTION_HALLUCINATION
                    explanation = "Extraction step failed to capture required fields (vendor name/date) due to ambiguous text format."
            elif step == "Classification":
                failing_type = MISCLASSIFICATION
                explanation = "Classification step misclassified a Purchase Order document as a Support Ticket because it contained email-like requests."
            elif step == "Summarization":
                failing_type = CONTEXT_LOSS
                explanation = "Summarization step failed to list key action items and deadlines, causing Context Loss."
            break
            
        # Check if the step is a propagation error
        elif score < 4 and is_propagation:
            # If we hit a propagation error, the root cause is upstream, which we should have caught
            # But just in case, note it
            pass
            
    # If a downstream step has a quality drop but we didn't flag an upstream step, check if it's a propagation
    if failing_step == "Unknown":
        for step in reversed(steps_order):
            eval_data = evaluations.get(step)
            if eval_data and eval_data.get("score", 5) < 4:
                failing_step = step
                if eval_data.get("is_propagation", False):
                    failing_type = PROPAGATION_ERROR
                    explanation = f"Step '{step}' produced incorrect output because it received incorrect fields from upstream steps."
                else:
                    failing_type = CONTEXT_LOSS
                    explanation = f"Quality drop observed at step '{step}'."
                break
                
    return {
        "root_cause_step": failing_step,
        "root_cause_type": failing_type,
        "explanation": explanation
    }

def analyze_trace_forensics(trace_id: str) -> Dict[str, Any]:
    """Runs backward forensics on a completed trace, saves results, and returns analysis."""
    trace_details = db.get_trace_details(trace_id)
    if not trace_details:
        return {"error": "Trace not found"}
        
    trace_obj = trace_details["trace"]
    spans = trace_details["spans"]
    
    # We walk backward to evaluate each span
    evaluations = {}
    for span in reversed(spans):
        step_name = span["name"]
        input_data = span["input_data"]
        output_data = span["output_data"]
        
        # Evaluate span
        eval_result = evaluate_span(step_name, input_data, output_data)
        evaluations[step_name] = eval_result
        
    # Diagnose root cause
    raw_text = trace_obj["input_doc"] or ""
    diagnosis = diagnose_root_cause(raw_text, evaluations)
    
    # Update SQLite database with diagnosis
    db.update_trace_root_cause(
        trace_id=trace_id,
        root_cause_step=diagnosis["root_cause_step"],
        root_cause_type=diagnosis["root_cause_type"],
        root_cause_explanation=diagnosis["explanation"]
    )
    
    # Re-save JSON trace file to incorporate forensics fields
    tracer_dir = os.path.dirname(os.path.abspath(__file__))
    traces_dir = os.path.join(tracer_dir, "traces")
    file_path = os.path.join(traces_dir, f"{trace_id}.json")
    
    updated_details = db.get_trace_details(trace_id)
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(updated_details, f, indent=2, ensure_ascii=False)
        
    return {
        "evaluations": evaluations,
        "diagnosis": diagnosis
    }
